#!/bin/bash
# PreToolUse (Write): warn when writing to vendored or generated paths.
cd "$CLAUDE_PROJECT_DIR" || exit 0

INPUT=$(cat)
FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

[[ -z "$FILE" ]] && exit 0

reason=""

case "$FILE" in
  */node_modules/*|node_modules/*)
    reason="Writing to node_modules/ - these are managed by npm, not edited directly" ;;
  */coverage/*|coverage/*|*/.nyc_output/*|.nyc_output/*)
    reason="Writing to coverage output directory - this is generated by npm run cover" ;;
esac

if [[ -n "$reason" ]]; then
  jq -n --arg reason "$reason" \
    '{"decision": "block", "reason": $reason}' || true
fi

exit 0
